In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import sqlalchemy

In [2]:
print(sqlalchemy.__version__)

2.0.48

In [3]:
from sqlalchemy import create_engine
from sqlalchemy import text

In [4]:
engine = create_engine('postgresql+psycopg2://postgres@localhost/train_reward_compare')

In [5]:
with engine.connect() as conn:
    result = conn.execute(text("select count(*) from onet.occupation_data"))
    print(result.fetchone())

(1016,)

In [9]:
file_nat = '../raw-data/bls-wage/oesm24nat/national_M2024_dl.xlsx'
file_sta = '../raw-data/bls-wage/oesm24st/state_M2024_dl.xlsx'
file_met = '../raw-data/bls-wage/oesm24ma/MSA_M2024_dl.xlsx'
file_bos = '../raw-data/bls-wage/oesm24ma/BOS_M2024_dl.xlsx'
file_nbs = '../raw-data/bls-wage/oesm24in4/natsector_M2024_dl.xlsx'

In [10]:
nat = pd.ExcelFile(file_nat)
sta = pd.ExcelFile(file_sta)
met = pd.ExcelFile(file_met)
bos = pd.ExcelFile(file_bos)
nbs = pd.ExcelFile(file_nbs)

In [11]:
print(nat.sheet_names)
print(sta.sheet_names)
print(met.sheet_names)
print(bos.sheet_names)
print(nbs.sheet_names)

['national_M2024_dl', 'Field Descriptions', 'UpdateTime', 'Filler']
['state_M2024_dl', 'Field Descriptions', 'UpdateTime', 'Filler']
['MSA_M2024_dl', 'Field Descriptions', 'UpdateTime', 'Filler']
['BOS_M2024_dl', 'Field Descriptions', 'UpdateTime', 'Filler']
['Natsector_M2024_dl', 'Field Descriptions', 'UpdateTime', 'Filler']

In [12]:
nat.parse('national_M2024_dl').head()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,23.8,37.89,60.44,29990,36730,49500,78810,125720,NaN,NaN
1,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,58.7,82.5,#,57010,79900,122090,171610,#,NaN,NaN
2,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1000,Top Executives,...,50.48,81.01,#,47510,68800,104990,168490,#,NaN,NaN
3,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1010,Chief Executives,...,99.24,#,#,73710,126080,206420,#,#,NaN,NaN
4,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,99.24,#,#,73710,126080,206420,#,#,NaN,NaN

In [13]:
nat.parse('Field Descriptions').head()

                             May 2024 OEWS Estimates Unnamed: 1 Unnamed: 2
0                                                NaN        NaN        NaN
1  Occupational Employment and Wage Statistics (O...        NaN        NaN
2    Bureau of Labor Statistics, Department of Labor        NaN        NaN
3                         website:  www.bls.gov/oes         NaN        NaN
4                            email: oewsinfo@bls.gov        NaN        NaN

In [14]:
nat.parse('UpdateTime').head()

        alldataupdate
0  09MAR2021:10:42:00

In [15]:
nat.parse('Filler').head()

Empty DataFrame
Columns: []
Index: []

In [16]:
nat_data = nat.parse('national_M2024_dl')

In [17]:
nat_desc = nat.parse('Field Descriptions')

In [18]:
nat_data.head()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,23.8,37.89,60.44,29990,36730,49500,78810,125720,NaN,NaN
1,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,58.7,82.5,#,57010,79900,122090,171610,#,NaN,NaN
2,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1000,Top Executives,...,50.48,81.01,#,47510,68800,104990,168490,#,NaN,NaN
3,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1010,Chief Executives,...,99.24,#,#,73710,126080,206420,#,#,NaN,NaN
4,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,99.24,#,#,73710,126080,206420,#,#,NaN,NaN

In [19]:
nat_data.columns = nat_data.columns.str.lower()

In [20]:
nat_data.head()

,area,area_title,area_type,prim_state,naics,naics_title,i_group,own_code,occ_code,occ_title,...,h_median,h_pct75,h_pct90,a_pct10,a_pct25,a_median,a_pct75,a_pct90,annual,hourly
0,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,23.8,37.89,60.44,29990,36730,49500,78810,125720,NaN,NaN
1,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,58.7,82.5,#,57010,79900,122090,171610,#,NaN,NaN
2,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1000,Top Executives,...,50.48,81.01,#,47510,68800,104990,168490,#,NaN,NaN
3,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1010,Chief Executives,...,99.24,#,#,73710,126080,206420,#,#,NaN,NaN
4,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,99.24,#,#,73710,126080,206420,#,#,NaN,NaN

In [21]:
nat_desc.columns = nat_desc.columns.str.lower()

In [23]:
nat_desc.iloc[:,:]

,may 2024 oews estimates,unnamed: 1,unnamed: 2
0,NaN,NaN,NaN
1,Occupational Employment and Wage Statistics (O...,NaN,NaN
2,"Bureau of Labor Statistics, Department of Labor",NaN,NaN
3,website: www.bls.gov/oes,NaN,NaN
4,email: oewsinfo@bls.gov,NaN,NaN
5,NaN,NaN,NaN
6,Not all fields are available for every type of...,NaN,NaN
7,NaN,NaN,NaN
8,Field,Field Description,NaN
9,area,"U.S. (99), state FIPS code, Metropolitan Stati...",NaN
10,area_title,Area name,NaN
11,area_type,Area type: 1= U.S.; 2= State; 3= U.S. Territor...,NaN
12,prim_state,"The primary state for the given area. ""US"" is ...",NaN
13,naics,North American Industry Classification System ...,NaN
14,naics_title,North American Industry Classification System ...,NaN
15,i_group,Industry level. Indicates cross-industry or NA...,NaN
16,own_code,Ownership type: 1= Federal Government; 2= Stat...,NaN
17,occ_code,The 6-digit Standard Occupational Classificati...,NaN
18,occ_title,SOC title or OEWS-specific title for the occup...,NaN
19,o_group,"SOC occupation level. For most occupations, th...",.
20,tot_emp,Estimated total employment rounded to the near...,NaN
21,emp_prse,Percent relative standard error (PRSE) for the...,NaN
22,jobs_1000,The number of jobs (employment) in the given o...,.
23,loc quotient,The location quotient represents the ratio of ...,NaN
24,pct_total,Percent of industry employment in the given oc...,.
25,pct_rpt,Percent of establishments reporting the given ...,NaN
26,h_mean,Mean hourly wage,NaN
27,a_mean,Mean annual wage,NaN
28,mean_prse,Percent relative standard error (PRSE) for the...,NaN
29,h_pct10,Hourly 10th percentile wage,NaN
30,h_pct25,Hourly 25th percentile wage,NaN
31,h_median,Hourly median wage (or the 50th percentile),NaN
32,h_pct75,Hourly 75th percentile wage,NaN
33,h_pct90,Hourly 90th percentile wage,NaN
34,a_pct10,Annual 10th percentile wage,NaN
35,a_pct25,Annual 25th percentile wage,NaN
36,a_median,Annual median wage (or the 50th percentile),NaN
37,a_pct75,Annual 75th percentile wage,NaN
38,a_pct90,Annual 90th percentile wage,NaN
39,annual,"Contains ""TRUE"" if only annual wages are relea...",.
40,hourly,"Contains ""TRUE"" if only hourly wages are relea...",.
41,NaN,NaN,NaN
42,Notes:,NaN,NaN
43,* = indicates that a wage estimate is not ava...,NaN,NaN
44,** = indicates that an employment estimate is...,NaN,NaN
45,# = indicates a wage equal to or greater than...,NaN,NaN
46,~ =indicates that the percent of establishment...,NaN,NaN

In [24]:
nat_desc = nat_desc.drop('unnamed: 2', axis=1)

In [25]:
nat_desc.head()

                             may 2024 oews estimates unnamed: 1
0                                                NaN        NaN
1  Occupational Employment and Wage Statistics (O...        NaN
2    Bureau of Labor Statistics, Department of Labor        NaN
3                         website:  www.bls.gov/oes         NaN
4                            email: oewsinfo@bls.gov        NaN

In [27]:
drop_index = nat_desc.index[0:8]

In [28]:
nat_desc_dropped = nat_desc.drop(drop_index)

In [29]:
nat_desc_dropped.head()

   may 2024 oews estimates                                         unnamed: 1
8                    Field                                  Field Description
9                     area  U.S. (99), state FIPS code, Metropolitan Stati...
10              area_title                                         Area name
11               area_type  Area type: 1= U.S.; 2= State; 3= U.S. Territor...
12              prim_state  The primary state for the given area. "US" is ...

In [30]:
nat_desc_new_header = nat_desc_dropped.iloc[0]

In [34]:
nat_desc_new = nat_desc_dropped[1:]

In [35]:
nat_desc_new.columns = nat_desc_new_header

In [36]:
nat_desc_new.head()

8        Field                                  Field Description
9         area  U.S. (99), state FIPS code, Metropolitan Stati...
10  area_title                                         Area name
11   area_type  Area type: 1= U.S.; 2= State; 3= U.S. Territor...
12  prim_state  The primary state for the given area. "US" is ...
13       naics  North American Industry Classification System ...

In [37]:
nat_desc_new = nat_desc_new.reset_index(drop=True)

In [38]:
nat_desc_new.head()

8       Field                                  Field Description
0        area  U.S. (99), state FIPS code, Metropolitan Stati...
1  area_title                                         Area name
2   area_type  Area type: 1= U.S.; 2= State; 3= U.S. Territor...
3  prim_state  The primary state for the given area. "US" is ...
4       naics  North American Industry Classification System ...

In [43]:
nat_desc_new.index.name = None

In [44]:
nat_desc_new.head()

8       Field                                  Field Description
0        area  U.S. (99), state FIPS code, Metropolitan Stati...
1  area_title                                         Area name
2   area_type  Area type: 1= U.S.; 2= State; 3= U.S. Territor...
3  prim_state  The primary state for the given area. "US" is ...
4       naics  North American Industry Classification System ...

In [49]:
nat_desc_new = nat_desc_new.drop(8, inplace=True)

KeyError: '[8] not found in axis'

In [51]:
nat_desc_new.head()

8       Field                                  Field Description
0        area  U.S. (99), state FIPS code, Metropolitan Stati...
1  area_title                                         Area name
2   area_type  Area type: 1= U.S.; 2= State; 3= U.S. Territor...
3  prim_state  The primary state for the given area. "US" is ...
4       naics  North American Industry Classification System ...

In [52]:
print(nat_desc_new.columns)

Index(['Field', 'Field Description'], dtype='object', name=8)

In [53]:
nat_desc_new.index.name=4

In [54]:
print(nat_desc_new.columns)

Index(['Field', 'Field Description'], dtype='object', name=8)

In [55]:
nat_desc_new = nat_desc_new.rename_axis(None, axis=1)

In [56]:
nat_desc_new.head()

        Field                                  Field Description
4
0        area  U.S. (99), state FIPS code, Metropolitan Stati...
1  area_title                                         Area name
2   area_type  Area type: 1= U.S.; 2= State; 3= U.S. Territor...
3  prim_state  The primary state for the given area. "US" is ...
4       naics  North American Industry Classification System ...

In [57]:
nat_desc_new.index.name=None

In [58]:
nat_desc_new.head()

        Field                                  Field Description
0        area  U.S. (99), state FIPS code, Metropolitan Stati...
1  area_title                                         Area name
2   area_type  Area type: 1= U.S.; 2= State; 3= U.S. Territor...
3  prim_state  The primary state for the given area. "US" is ...
4       naics  North American Industry Classification System ...